services:

    # Application
    app:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
                - APP_PORT=8000
        container_name: laravel_app_container
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            database:
                condition: service_healthy
            redis:
                condition: service_healthy

    # Database Server
    database:
        image: mysql:8.4
        container_name: mysql_container
        ports: 
            - 3306:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - db-data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u${DB_USERNAME}", "-p${DB_PASSWORD}"]
            interval: 10s
            retries: 5
            start_period: 240s
            timeout: 5s

    # Redis Server
    redis:
        image: redis:alpine
        container_name: redis_container
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        ports: 
            - 6379:6379
        volumes:
            - ./storage/redis/data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            retries: 3
            timeout: 3s

volumes:
    db-data: